name: webgl-build
on:
  workflow_dispatch:

jobs:
  build:
    name: Run the WebGL build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - webgl-st: 0
            label: "-Compressed"
          - webgl-st: 1
            label: ""

    steps:
      - uses: actions/checkout@v2

      - name: Configure settings
        run: |
          sed -i -e "s/webGLDecompressionFallback: [0-9]/webGLDecompressionFallback: ${{ matrix.webgl-st }}/" ProjectSettings/ProjectSettings.asset
          cat ProjectSettings/ProjectSettings.asset | grep webGLDecompressionFallback

      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # 今回は WebGL ビルドを行いたいため WebGL を指定する
          # WebGL 以外の指定可能な値は下記に記載の値が利用可能
          # ref: https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: WebGL
          unityVersion: 2020.2.7f1

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build${{ matrix.label }}
          path: build
